name: Run Regal Lint Check
on: [push]
jobs:
  lint-rego:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup Regal
      uses: StyraInc/setup-regal@v0.2.0
      with:
        version: latest

    - name: Lint
      run: regal lint --format github ./policies